#ifndef DDENETWORKUTILS_GLOBAL_H
#define DDENETWORKUTILS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DDENETWORKUTILS_LIBRARY)
#  define DDENETWORKUTILSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DDENETWORKUTILSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DDENETWORKUTILS_GLOBAL_H
